# Build Stage
FROM ubuntu:20.04 as builder

## Install build dependencies.
RUN apt-get update && \
    DEBIAN_FRONTEND=noninteractive apt-get install -y clang curl 

RUN apt-get update && apt-get -y upgrade && apt-get install -y cmake
# RUN curl -sSL https://cmake.org/files/v3.5/cmake-3.5.2-Linux-x86_64.tar.gz | tar -xzC /opt

#RUN apt-get install software-properties-common && add-apt-repository ppa:george-edison55/cmake-3.x
#RUN apt-get update && apt-get install cmake

RUN curl --proto "=https" --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
RUN ${HOME}/.cargo/bin/rustup default nightly
RUN ${HOME}/.cargo/bin/cargo install -f cargo-fuzz

## Add source code to the build stage.
ADD . /pelikan
WORKDIR /pelikan

RUN cd src/protocol/ping/fuzz && ${HOME}/.cargo/bin/cargo fuzz build

# Package Stage
FROM ubuntu:20.04

COPY --from=builder pelikan/src/protocol/ping/fuzz/target/x86_64-unknown-linux-gnu/release/ping /
